// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieSite.Models;

namespace MovieSite.Migrations
{
    [DbContext(typeof(MovieFormsContext))]
    [Migration("20220126220826_initials")]
    partial class initials
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("MovieSite.Models.MovieModel", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Director = "Shawn Levy",
                            Edited = false,
                            Notes = "Ryan Reynolds is the best ever...",
                            Rating = "PG",
                            Title = "Free Guy",
                            Year = 2021
                        },
                        new
                        {
                            MovieId = 2,
                            Director = "Taika Waititi",
                            Edited = false,
                            Notes = "Powerful",
                            Rating = "PG-13",
                            Title = "JoJo Rabbit",
                            Year = 2019
                        },
                        new
                        {
                            MovieId = 3,
                            Director = "Jared Hess",
                            Edited = false,
                            Notes = "Hilarious",
                            Rating = "PG",
                            Title = "Napoleon Dynamite",
                            Year = 2004
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
